---
- name: instalando docker
  hosts: docker

  tasks:
   - name: instalando pacotes
     apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
     with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
     when: ansible_os_family == "Debian" 

   - name: Adiciona GPG key
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
     when: ansible_os_family == "Debian"

   - name: Adiciona repositorio
     apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu "{{ ansible_distribution_release }}" stable
      state: present
     when: ansible_os_family == "Debian"

   - name: instalando Docker
     package:
      name: docker-ce
      state: present
      update_cache: yes
